### PR TITLE
Add Bayes Factors

### PR DESCRIPTION
**Pull request by anirudhacharya**
Adds bayes factors for - binomial tests, Pearson correlation, T-test

### CODE REVIEW

**Review by clementpoiret — APPROVED** [review]
Thanks a lot for your help! Nice job :+1:

**Comment by anirudhacharya** [comment]
> NB: In the long term, I think we should consider avoiding the usage of PyCall (like in SciPy.jl), this is okay for now anyway :)

@clementpoiret Yes, I agree. I used it for computing the integrands. Do you know of any packages I could use for computing integrands?

**Comment by clementpoiret** [comment]
@anirudhacharya what about https://github.com/JuliaMath/QuadGK.jl ?

**Comment by anirudhacharya** [comment]
@clementpoiret looks like it should work. I will check out.

Also I have this branch which adds docs using Documenter.jl https://github.com/clementpoiret/Pingouin.jl/compare/master...anirudhacharya:docs. Do you think it can be added to the repo?

**Comment by clementpoiret** [comment]
Of course, I never used Documenter.jl but I think it's a great addition

**Pull request merged**
